export enum CurrencyType {
    mana = "Mana",
    maxMana = "Max Mana",
    knowledge = "Knowledge",
    maxKnowledge = "Max Knowledge",
    infraCrystal = "Infrared Crystal",
    maxInfra = "Max Infrared Crystal",
    redCrystal = "Red Crystal",
    maxRed = "Max Red Crystal",
    orangeCrystal = "Orange Crystal",
    maxOrange = "Max Orange Crystal",
    yellowCrystal = "Yellow Crystal",
    maxYellow = "Max Yellow Crystal",
    greenCrystal = "Green Crystal",
    maxGreen = "Max Green Crystal",
    blank = "<blank>",
}