export enum SkillId {
    Dexterity,
    Speed,
    Strength,
    Endurance,
    Construction,
    Absorption,
    Perception,
    Intelligence,
    SpellCasting,
    Social,
    CloseCombat,
    RangedCombat,
    MagicCombat,
    Blank,
}