export enum SkillId {
    Gathering,
    Exploration,
    ToolUse,
    Forging,
    Construction,
    Absorption,
    Perception,
    Intelligence,
    SpellCasting,
    Social,
    CloseCombat,
    RangedCombat,
    MagicCombat,
    Blank,
}